name: dms
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.77+142

environment:
  sdk: '>=3.5.4 <4.0.0'
#  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  logger: ^2.6.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  oktoast: ^3.4.0
  omni_datetime_picker: ^2.0.4
  permission_handler: ^12.0.0+1
  http: ^1.4.0
  socket_io_client: ^3.1.2
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  vibration: ^3.1.3
  google_maps_flutter: ^2.10.1
  geocoding: ^4.0.0
  flutter_polyline_points: ^2.1.0
  overlay_support: ^2.1.0
  persistent_bottom_nav_bar: ^6.2.1
  firebase_messaging: ^15.2.7
  cloud_firestore: ^5.6.9
  flutter_slidable: ^3.1.2
  dotted_border: ^2.1.0
  flutter_widget_from_html_core: ^0.16.0
  enefty_icons: ^1.0.8
  mobile_scanner: ^7.0.0
  modal_bottom_sheet: ^3.0.0
  open_file: ^3.5.10
  carousel_slider: ^5.1.1
  network_info_plus: ^6.1.4
  flutter_local_notifications: ^19.3.0
  geolocator: ^13.0.4
  geolocator_android: 4.6.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  fl_chart: ^0.69.0
  flutter_charts: ^0.5.2
  syncfusion_flutter_charts: ^29.1.37
  flutter_email_sender: ^7.0.0
  percent_indicator: ^4.2.5
#  getwidget: ^4.0.0
  camera: ^0.11.1
  intl: ^0.20.2
  googleapis_auth: ^2.0.0
  font_awesome_flutter: ^10.8.0
  material_design_icons_flutter: ^7.0.7296
  another_transformer_page_view: ^2.0.1
  get_storage: ^2.1.1
  open_store: ^0.5.0
  flutter_update_dialog: ^2.0.0
  sign_in_button: ^4.0.1
  fluentui_system_icons: ^1.1.273
  table_calendar: ^3.2.0
  location: ^8.0.1
  sliding_up_panel: ^2.0.0+1
  image_picker: ^1.1.2 #check
  photo_view: ^0.15.0
  flutter_snake_navigationbar: ^0.6.1
  flutter_advanced_switch: ^3.1.0
  file_picker: ^10.2.0
  syncfusion_flutter_datagrid: ^29.1.38
  map_picker: ^0.0.3
  flutter_svg: ^2.2.0
  loading_animation_widget: ^1.3.0
  sticky_headers: ^0.3.0+2
  gs1_barcode_parser: ^1.1.2
  decimal: ^2.1.0

  shorebird_code_push: 2.0.3
  restart_app:
    git:
      url: https://github.com/putpin/restart_app
  dvhcvn: ^2.1.20250301
  expansion_tile_card: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_dms.png"
# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/icon_svg/
    - assets/images/
    - assets/illustion/
    - assets/locales/vi.json
    - assets/locales/en.json
    - assets/data.json
    - assets/icons/
    - assets/rive/
    - shorebird.yaml